get http://localhost:3000/api/getOptionsData?name=AAPL
###
get http://localhost:3000/api/getOptions?name=AAPL&optionDate=2023-01-20
###
post http://localhost:3001/api/getOptionsArr HTTP/1.1
content-type: application/json

{
    "data":[
        {
            "name": "XOM",
            "type": "put",
            "strike": 97.5,
            "date": "2023-01-20"
        },
        {
            "name": "AAPL",
            "strike": 135,
            "type": "call",
            "date": "2023-01-20"
        }
    ]
}

