get http://localhost:3000/api/getOptionsData?name=AAPL
###
get https://coda-options.vercel.app/api/getOptionsData?name=AAPL

###
get http://localhost:3001/api/getOptions?name=AAPL&optionDate=2023-07-21&optionsType=calls
###
get https://coda-options.vercel.app/api/getOptions?name=AAPL&optionDate=2023-01-20

###
post http://localhost:3000/api/getOptionsArr HTTP/1.1
content-type: application/json

{
    "data":[
        {
            "name": "AAPL",
            "strike": 145,
            "type": "put",
            "date": "2023-01-20"
        },
        {
            "name": "XOM",
            "type": "put",
            "strike": 97.5,
            "date": "2023-01-20"
        },
        {
            "name": "AAPL",
            "strike": 135,
            "type": "put",
            "date": "2023-01-20"
        }
    ]
}

###
post https://coda-options.vercel.app/api/getOptionsArr HTTP/1.1
content-type: application/json
{
    "data":[
       {
            "name": "AAPL",
            "strike": 145,
            "type": "put",
            "date": "2023-01-20"
        },
        {
            "name": "XOM",
            "type": "put",
            "strike": 97.5,
            "date": "2023-01-20"
        },
        {
            "name": "AAPL",
            "strike": 135,
            "type": "put",
            "date": "2023-01-20"
        }
    ]
}

###
get http://localhost:3000/api/contractsByExpiration?ticker=AAPL&expirationDate=2023-01-20
###
get http://localhost:3000/api/contractsByExpiration?ticker=AAPL&expirationDate=2023-01-20&bustCache=true&cacheTTL=600